### PR TITLE
Remove hash checking

### PR DESCRIPTION
**Pull request by wpears**
Removes hash checking and morphs it into a schema check. Mostly leans on existing tests and the fieldFilter module (if the schema check fails, it returns an error from within pumped pipeline which destroys all streams in the pipeline and reports the error)

### CODE REVIEW

**Comment by hkeeler** [comment]
Looks like Travis itself [blew up](https://travis-ci.org/cfpb/grasshopper-loader/builds/97484113#L872) while running the tests in Docker:

```
Broadcast message from root@testing-gce-61e31d8a-051e-46fb-807b-94d57736bef9
	(unknown) at 16:45 ...

The system is going down for power off NOW!
The command "docker run --rm -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" hmda/loader npm test -- -h $(echo "$ES_HOST")" exited with 143.
```

@wpears, did you see anything like this in your previous Travis/Docker wranglings?

I'm kicking the build back off now...

**Comment by hkeeler** [comment]
...and then it stalled out here: https://travis-ci.org/cfpb/grasshopper-loader#L870.  Kicking it off again.

**Comment by hkeeler** [comment]
I think we're stepping on each others toes.  I'll step away...

**Comment by wpears** [comment]
Yeah I'm really at a loss here, been working on this for a couple hours.

It works locally, it works locally in Docker... and it fails in Travis--using Docker.

So if it works locally with Docker but not on Travis with Docker... is that a bug in Travis's implementation of Dockerized builds?

**Comment by hkeeler** [comment]
Looks good.  Created https://github.com/cfpb/grasshopper-loader/issues/155 so we don't forget about the tests that got commented out to make Travis happy.

**Pull request merged**
