### PR TITLE
added Ohio north/south to metadata

### PR DESCRIPTION
**Pull request by kgudel**

### CODE REVIEW

**Comment by wpears** [comment]
Will merge once ohio_north and ohio_south are combined :rocket:

**Comment by awolfe76** [comment]
@kgudel @wpears does this still need merged?

**Comment by wpears** [comment]
Yeah, but waiting for `ohio_south` and `ohio_north` to be combined into just `ohio`

**Comment by kgudel** [comment]
One second, messed up Tennessee

**Comment by wpears** [comment]
Better late than never :+1: (the failed test is due to unavailable credentials)

**Pull request merged**
